name: phylogpn-replication
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  # deep learning
  - pytorch::pytorch=2.1.*
  - pytorch::torchvision
  - pytorch::pytorch-cuda=11.8
  # bioinformatics
  - bioconda::cyvcf2
  - bioconda::pyfaidx
  - bioconda::pyliftover
  # data
  - pandas
  - pyarrow
  - openpyxl
  - tqdm
  # stats / plotting
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pip:
    # HuggingFace
    - transformers>=4.38.0
    - datasets>=2.18.0
    - huggingface-hub
    - accelerate
    # GPN package (song lab)
    - git+https://github.com/songlab-cal/gpn.git
    # Caduceus
    - caduceus-dna
